eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6999/eureka/
  instance:
    hostname: localhost
    
microservice:
  company-portal:
    endpoints:
      endpoint:
        uri: http://employee-portal/employee/company/
